POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "kdsfgsdfgrn",
  "name": "kssdfgsdfgrn",
  "password": "kishd",
  "gender": "male",
  "location": "Detroitasdfasd"
}

###

GET http://localhost:3000/register/
Content-Type: application/json

{
  "username": "kishore",
  "password": "kishore123"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "kishore",
  "password": "kishore123"
}

###

PUT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "kishore",
  "oldPassword": "kishore123",
  "newPassword": "kishore1234"
}

###
